spring:
  application:
    name:
      paymentservice
    r2dbc:
      url: jdbc:mysql://localhost:3306/paymentservice?useSSL=false&serverTimezone=UTC
      username: myuser
      password: secret
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  devtools:
    liveReload:
      enabled: true

PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com
